 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default
         
     steps:
       - checkout
       - run:
          command: cd Engines && dotnet build && cd ../Utilities/Tests && dotnet build && dotnet test
          shell: bash.exe
       - store_test_results:
          path: test-results

